Controllers/PricesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RouterLab;

namespace RouterLab.Controllers
{
    public class PricesController : Controller
    {
        private readonly RouterBaseContext _context;

        public PricesController(RouterBaseContext context)
        {
            _context = context;
        }

        // GET: Prices
        public async Task<IActionResult> Index()
        {
            return View(await _context.Price.ToListAsync());
        }
        
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {

            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {

                    using var stream = new FileStream(fileExcel.FileName, FileMode.Create);
                    await fileExcel.CopyToAsync(stream);
                    using XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled);
                    List<List<string>> Errors = new List<List<string>>();
                    foreach (IXLWorksheet worksheet in workBook.Worksheets)
                    {
                        Price price;
                        var g = (from pr in _context.Price
                                 where pr.Price1 == worksheet.Name
                                 select pr).ToList();
                        if (g.Count > 0)
                        {
                            price = g[0];
                        }
                        else
                        {
                            price = new Price
                            {
                                Price1 = worksheet.Name
                            };
                            _context.Price.Add(price);

                        }
                        await _context.SaveChangesAsync();
                        foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
                        {
                            Router router = new Router();
                            string name = row.Cell(1).Value.ToString();
                            if (name.Length > 50 || name.Length < 3) continue;
                            var f = (from rou in _context.Router where rou.Name == name select rou).ToList();
                            if (f.Count() > 0)
                            {
                                router = f[0];
                                await _context.SaveChangesAsync();
                            }
                            else
                            {
                                router.Name = row.Cell(1).Value.ToString();
                                router.Price = price;
                                string name1 = row.Cell(2).Value.ToString();
                                if (name1.Length > 50 || name1.Length < 3) continue;
                                Speed speed;
                                var a = (from pr in _context.Speed
                                         where pr.Speed1 == row.Cell(2).Value.ToString()
                                         select pr).ToList();
                                if (a.Count() > 0)
                                {
                                    speed = a[0];
                                    router.Speed = speed;
                                }
                                else
                                {
                                    speed = new Speed
                                    {
                                        Speed1 = row.Cell(2).Value.ToString()
                                    };
                                    _context.Add(speed);
                                    router.Speed = speed;
                                }
                                string name2 = row.Cell(3).Value.ToString();
                               
                                if (name2.Length > 50 || name2.Length < 2) continue;
                                Diapason diapason;
                                var b = (from pr in _context.Diapason
                                         where pr.Diapason1 == row.Cell(3).Value.ToString()
                                         select pr).ToList();
                                if (b.Count() > 0)
                                {
                                    diapason = b[0];
                                    router.Diapason = diapason;
                                }
                                else
                                {
                                    diapason = new Diapason
                                    {
                                        Diapason1 = row.Cell(3).Value.ToString()
                                    };
                                    _context.Add(diapason);
                                    router.Diapason = diapason;
                                }
                                _context.Router.Add(router);
                                await _context.SaveChangesAsync();
                            }
                        }
                    }
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index", "Routers");
        }
        public ActionResult Export(int? id)
        {
            using XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled);
            string price = _context.Price.FirstOrDefault(m => m.PriceId == id).Price1;
            var priceRouters = _context.Router.Where(f => f.PriceId == id).Include(f => f.Speed).Include(f => f.Diapason).Include(f => f.Price).ToList();
            var worksheet = workbook.Worksheets.Add(price);
            foreach (var g in priceRouters)
            {
                worksheet.Cell("A1").Value = "Назва моделі роутера";
                worksheet.Cell("B1").Value = "Рік";
                worksheet.Cell("C1").Value = "Швидкість";
                worksheet.Cell("D1").Value = "Режим роботи";
                worksheet.Row(1).Style.Font.Bold = true;
                for (int i = 0; i < priceRouters.Count; i++)
                {
                    worksheet.Cell(i + 2, 1).Value = priceRouters[i].Name;
                    worksheet.Cell(i + 2, 2).Value = priceRouters[i].Year;
                    worksheet.Cell(i + 2, 3).Value = priceRouters[i].Speed.Speed1;
                    worksheet.Cell(i + 2, 4).Value = priceRouters[i].Diapason.Diapason1;
                }
            }
            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            stream.Flush();

            return new FileContentResult(stream.ToArray(),
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            {
                FileDownloadName = $"LabRouter_{DateTime.UtcNow.ToShortDateString()}.xlsx"
            };
        }
        // GET: Prices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var price = await _context.Price
                .FirstOrDefaultAsync(m => m.PriceId == id);
            if (price == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Routers", new { prId = id });
        }

        // GET: Prices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Prices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PriceId,Price1")] Price price)
        {
            if (ModelState.IsValid)
            {
                _context.Add(price);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(price);
        }

        // GET: Prices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var price = await _context.Price.FindAsync(id);
            if (price == null)
            {
                return NotFound();
            }
            return View(price);
        }

        // POST: Prices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PriceId,Price1")] Price price)
        {
            if (id != price.PriceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(price);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PriceExists(price.PriceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(price);
        }

        // GET: Prices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();

Controllers/RoutersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RouterLab;

namespace RouterLab.Controllers
{
    public class RoutersController : Controller
    {
        private readonly RouterBaseContext _context;

        public RoutersController(RouterBaseContext context)
        {
            _context = context;
        }

        // GET: Routers
        public async Task<IActionResult> Index(int id, int SpId , int dId, int prId)
        {
            if (id != 0)
            {
                var routerBaseContext1 = _context.Router.Where(r=>r.RouterId==id).Include(r => r.Diapason).Include(r => r.Price).Include(r => r.Speed);
                return View(await routerBaseContext1.ToListAsync());
            }
            if (SpId != 0)
            {
                var routerBaseContext1 = _context.Router.Where(r => r.SpeedId == SpId).Include(r => r.Diapason).Include(r => r.Price).Include(r => r.Speed);
                return View(await routerBaseContext1.ToListAsync());
            }
            if (dId != 0)
            {
                var routerBaseContext1 = _context.Router.Where(r => r.DiapasonId== dId).Include(r => r.Diapason).Include(r => r.Price).Include(r => r.Speed);
                return View(await routerBaseContext1.ToListAsync());
            }
            if (prId != 0)
            {
                var routerBaseContext1 = _context.Router.Where(r => r.PriceId == prId).Include(r => r.Diapason).Include(r => r.Price).Include(r => r.Speed);
                return View(await routerBaseContext1.ToListAsync());
            }
            var routerBaseContext = _context.Router.Include(r => r.Diapason).Include(r => r.Price).Include(r => r.Speed);
            return View(await routerBaseContext.ToListAsync());
        }

        // GET: Routers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var router = await _context.Router
                .Include(r => r.Diapason)
                .Include(r => r.Price)
                .Include(r => r.Speed)
                .FirstOrDefaultAsync(m => m.RouterId == id);
            if (router == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "RouterStandarts", new { id });
        }

        // GET: Routers/Create
        public IActionResult Create()
        {
            ViewData["DiapasonId"] = new SelectList(_context.Diapason, "DiapasonId", "Diapason1");
            ViewData["PriceId"] = new SelectList(_context.Price, "PriceId", "Price1");
            ViewData["SpeedId"] = new SelectList(_context.Speed, "SpeedId", "Speed1");
            return View();
        }

        // POST: Routers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RouterId,Name,Year,PriceId,DiapasonId,SpeedId")] Router router)
        {
            if (ModelState.IsValid)
            {
                _context.Add(router);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DiapasonId"] = new SelectList(_context.Diapason, "DiapasonId", "Diapason1", router.DiapasonId);
            ViewData["PriceId"] = new SelectList(_context.Price, "PriceId", "Price1", router.PriceId);
            ViewData["SpeedId"] = new SelectList(_context.Speed, "SpeedId", "Speed1", router.SpeedId);
            return View(router);
        }

        // GET: Routers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var router = await _context.Router.FindAsync(id);
            if (router == null)
            {
                return NotFound();
            }
            ViewData["DiapasonId"] = new SelectList(_context.Diapason, "DiapasonId", "Diapason1", router.DiapasonId);
            ViewData["PriceId"] = new SelectList(_context.Price, "PriceId", "Price1", router.PriceId);
            ViewData["SpeedId"] = new SelectList(_context.Speed, "SpeedId", "Speed1", router.SpeedId);
            return View(router);
        }

        // POST: Routers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RouterId,Name,Year,PriceId,DiapasonId,SpeedId")] Router router)
        {
            if (id != router.RouterId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(router);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RouterExists(router.RouterId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DiapasonId"] = new SelectList(_context.Diapason, "DiapasonId", "Diapason1", router.DiapasonId);
            ViewData["PriceId"] = new SelectList(_context.Price, "PriceId", "Price1", router.PriceId);
            ViewData["SpeedId"] = new SelectList(_context.Speed, "SpeedId", "Speed1", router.SpeedId);
            return View(router);
        }

        // GET: Routers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var router = await _context.Router
                .Include(r => r.Diapason)
                .Include(r => r.Price)
                .Include(r => r.Speed)
                .FirstOrDefaultAsync(m => m.RouterId == id);
            if (router == null)
            {
                return NotFound();
            }

            return View(router);
        }

        // POST: Routers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var routSt= _context.RouterStandart.Where(d => d.RouterId== id).Include(d => d.Router).Include(d => d.Standart).ToList();
            _context.RouterStandart.RemoveRange(routSt);
            
            var router = await _context.Router.FindAsync(id);
            _context.Router.Remove(router);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RouterExists(int id)
        {
            return _context.Router.Any(e => e.RouterId == id);
        }
    }
}

Views/Routers/Create.cshtml
@model RouterLab.Router

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Router</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceId" class="control-label"></label>
                <select asp-for="PriceId" class ="form-control" asp-items="ViewBag.PriceId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DiapasonId" class="control-label"></label>
                <select asp-for="DiapasonId" class ="form-control" asp-items="ViewBag.DiapasonId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SpeedId" class="control-label"></label>
                <select asp-for="SpeedId" class ="form-control" asp-items="ViewBag.SpeedId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Routers/Delete.cshtml
@model RouterLab.Router

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Router</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diapason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diapason.Diapason1)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price.Price1)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Speed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Speed.Speed1)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RouterId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Routers/Details.cshtml
@model RouterLab.Router

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Router</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diapason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diapason.Diapason1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price.Price1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Speed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Speed.Speed1)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RouterId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Routers/Edit.cshtml
@model RouterLab.Router

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Router</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RouterId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceId" class="control-label"></label>
                <select asp-for="PriceId" class="form-control" asp-items="ViewBag.PriceId"></select>
                <span asp-validation-for="PriceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiapasonId" class="control-label"></label>
                <select asp-for="DiapasonId" class="form-control" asp-items="ViewBag.DiapasonId"></select>
                <span asp-validation-for="DiapasonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeedId" class="control-label"></label>
                <select asp-for="SpeedId" class="form-control" asp-items="ViewBag.SpeedId"></select>
                <span asp-validation-for="SpeedId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Routers/Index.cshtml
@model IEnumerable<RouterLab.Router>

@{
    ViewData["Title"] = "Index";
}

<h1>Роутери</h1>

<p>
    <a asp-action="Create">Додати</a>
</p>

<div>
    <h3>Select Excel-file for download</h3>
    @using (Html.BeginForm("Import", "Prices", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Download Excel-file:
            <input type="file" name="fileExcel" id="fileExcel" />
            <div>
                <input type="submit" value="Download" />
            </div>
        </div>
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diapason)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Speed)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diapason.Diapason1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price.Price1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Speed.Speed1)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.RouterId">Змінити</a> |
                    <a asp-action="Details" asp-route-id="@item.RouterId">Стандарти</a> |
                    <a asp-action="Delete" asp-route-id="@item.RouterId">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>